@startuml delete food assigned

actor "Actor"
boundary "api"
control "FoodController"
entity "FoodUser"
database "food_user"

"Actor" ->  "api" : /api/food/delete
activate api
"api" -> "FoodController" : delete()
activate FoodController
"FoodController" ->  "FoodController" : FormValidation()
"FoodController" ->  "FoodUser" : update()
activate FoodUser
"FoodUser" ->  "food_user" : update
activate food_user
"food_user" --> "FoodUser" : data
deactivate food_user
"FoodUser" --> "FoodController": data
deactivate FoodUser
"FoodController" --> "api" : return data with status HTTP 200
deactivate FoodController
deactivate api
@enduml