@startuml assign food

actor "Actor"
boundary "api"
control "FoodController"
entity "Food"
database "food_user"

"Actor" ->  "api" : /api/food/assign
activate api
"api" -> "FoodController" : assign()
activate FoodController
"FoodController" ->  "FoodController" : FormValidation()
"FoodController" ->  "Food" : create()
activate Food
"Food" ->  "food_user" : insert or update
activate food_user
"food_user" --> "Food" : data
deactivate food_user
"Food" --> "FoodController": data
deactivate Food
"FoodController" --> "api" : return data with status HTTP 200
deactivate FoodController
deactivate api
@enduml