@startuml assign food

actor "Actor"
boundary "api"
control "FoodController"
entity "FoodUser"
database "food_user"

"Actor" ->  "api" : /api/food/assign
activate api
"api" -> "FoodController" : assign()
activate FoodController
"FoodController" ->  "FoodController" : FormValidation()
"FoodController" ->  "FoodUser" : create()
activate FoodUser
"FoodUser" ->  "food_user" : insert or update
activate food_user
"food_user" --> "FoodUser" : data
deactivate food_user
"FoodUser" --> "FoodController": data
deactivate FoodUser
"FoodController" --> "api" : return data with status HTTP 200
deactivate FoodController
deactivate api
@enduml